import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
const SERVICE_ROLE = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const db = createClient(SUPABASE_URL, SERVICE_ROLE, { auth: { persistSession: false, autoRefreshToken: false } });
const encoder = new TextEncoder();
const cors = {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, apikey, content-type, x-msk-session","Access-Control-Allow-Methods":"GET,POST,OPTIONS","Content-Type":"application/json"};
const json = (body: unknown, status = 200) => new Response(JSON.stringify(body), { status, headers: cors });
const b64url = (bytes: Uint8Array) => btoa(String.fromCharCode(...bytes)).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/,"" );
const sha256 = async (value: string) => b64url(new Uint8Array(await crypto.subtle.digest("SHA-256", encoder.encode(value))));
const bearer = (req: Request) => (req.headers.get("authorization") || "").replace(/^Bearer\s+/i, "").trim();
const env = (name: string) => { const value = String(Deno.env.get(name) || "").trim(); if (!value) throw new Error(`Secret ausente: ${name}`); return value; };
const hmac = async (value: string) => { const key = await crypto.subtle.importKey("raw", encoder.encode(env("MSK_STATE_SECRET")), { name: "HMAC", hash: "SHA-256" }, false, ["sign"]); return b64url(new Uint8Array(await crypto.subtle.sign("HMAC", key, encoder.encode(value)))); };
const makeState = async (projectId: string, returnUrl: string, repository: string, userId: string) => { const payload = b64url(encoder.encode(JSON.stringify({ projectId, returnUrl, repository, userId, exp: Date.now() + 15 * 60_000 }))); return `${payload}.${await hmac(payload)}`; };
async function currentUser(req: Request){const token=bearer(req);if(!token||token.startsWith("sb_publishable_"))return null;const {data,error}=await db.auth.getUser(token);return error?null:data.user;}
async function sessionMatches(projectId:string,token:string){if(!token)return false;const {data}=await db.from("msk_projects").select("session_token_hash").eq("lovable_project_id",projectId).maybeSingle();return !!data?.session_token_hash&&data.session_token_hash===await sha256(token);}
async function installationOwner(installationId:number){if(!installationId)return null;const {data}=await db.from("msk_github_installations").select("user_id,revoked_at").eq("installation_id",installationId).maybeSingle();return data||null;}
async function claimProjectForUser(projectId:string,userId:string,sessionToken:string){if(!await sessionMatches(projectId,sessionToken))return{ok:false as const,code:"MSK_SESSION_REQUIRED"};const {data:project}=await db.from("msk_projects").select("user_id,github_installation_id").eq("lovable_project_id",projectId).maybeSingle();if(!project?.github_installation_id)return{ok:false as const,code:"GITHUB_NOT_CONNECTED"};if(project.user_id&&String(project.user_id)!==userId)return{ok:false as const,code:"PROJECT_OWNERSHIP_MISMATCH"};const installationId=Number(project.github_installation_id);const existing=await installationOwner(installationId);if(existing?.user_id&&String(existing.user_id)!==userId)return{ok:false as const,code:"GITHUB_INSTALLATION_OWNERSHIP_MISMATCH"};const now=new Date().toISOString();const {error:projectError}=await db.from("msk_projects").update({user_id:userId,updated_at:now}).eq("lovable_project_id",projectId);if(projectError)return{ok:false as const,code:"PROJECT_BIND_FAILED"};const {error:installError}=await db.from("msk_github_installations").upsert({user_id:userId,installation_id:installationId,revoked_at:null,last_validated_at:now,updated_at:now},{onConflict:"installation_id"});if(installError)return{ok:false as const,code:"GITHUB_INSTALLATION_BIND_FAILED"};return{ok:true as const,installationId};}
async function ownedProject(projectId:string,userId:string){const {data}=await db.from("msk_projects").select("user_id,github_installation_id,github_owner,github_repo").eq("lovable_project_id",projectId).maybeSingle();if(!data)return{ok:true as const,project:null};if(data.user_id&&String(data.user_id)!==userId)return{ok:false as const,code:"PROJECT_OWNERSHIP_MISMATCH"};if(data.github_installation_id){const installation=await installationOwner(Number(data.github_installation_id));if(installation?.user_id&&String(installation.user_id)!==userId)return{ok:false as const,code:"GITHUB_INSTALLATION_OWNERSHIP_MISMATCH"};if(installation?.revoked_at)return{ok:false as const,code:"GITHUB_RECONNECT_REQUIRED"};}return{ok:true as const,project:data};}
async function callCore(req:Request,action:string,body:any,overrideBody?:any){const headers:Record<string,string>={"Content-Type":"application/json","apikey":req.headers.get("apikey")||SERVICE_ROLE};const auth=req.headers.get("authorization");const session=req.headers.get("x-msk-session");if(auth)headers.Authorization=auth;if(session)headers["x-msk-session"]=session;return fetch(`${SUPABASE_URL}/functions/v1/msk-agent?action=${encodeURIComponent(action)}`,{method:"POST",headers,body:JSON.stringify(overrideBody??body)});}
async function readCoreResponse(response:Response){const text=await response.text();try{return text?JSON.parse(text):{};}catch{return{error:text||`Falha HTTP ${response.status}`};}}
Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(req.method!=="POST")return json({error:"Método inválido."},405);const url=new URL(req.url);const action=url.searchParams.get("action")||"status";if(action==="health")return json({ok:true,service:"msk-agent-user",version:"1.2.0",multi_user:true});const user=await currentUser(req);if(!user)return json({connected:false,error:"Entre na sua conta MSK para conectar o seu GitHub.",code:"MSK_ACCOUNT_REQUIRED"},401);const userId=String(user.id);const body=await req.json().catch(()=>({}));const projectId=String(body?.lovable_project_id||"").trim();if(!/^[0-9a-f-]{36}$/i.test(projectId))return json({error:"ID de projeto inválido."},400);const sessionToken=String(req.headers.get("x-msk-session")||"");let ownership=await ownedProject(projectId,userId);if(!ownership.ok)return json({connected:false,error:"Este projeto ou esta instalação GitHub pertence a outra conta MSK.",code:ownership.code},403);if(ownership.project&&!ownership.project.user_id&&sessionToken){const claim=await claimProjectForUser(projectId,userId,sessionToken);if(!claim.ok&&claim.code!=="GITHUB_NOT_CONNECTED")return json({connected:false,error:"Não foi possível confirmar que esta conexão GitHub pertence à sua conta MSK.",code:claim.code},403);ownership=await ownedProject(projectId,userId);}
if(action==="connect"){
  const {data:ownInstalls}=await db.from("msk_github_installations").select("installation_id").eq("user_id",userId).is("revoked_at",null).limit(20);
  const ownIds=new Set((ownInstalls||[]).map((row:any)=>Number(row.installation_id)));
  const projectInstallationId=Number(ownership.project?.github_installation_id||0);
  const legacyUnclaimed=!!projectInstallationId&&!ownership.project?.user_id&&!ownIds.has(projectInstallationId)&&!sessionToken;
  if(legacyUnclaimed){
    const returnUrl=/^https:\/\/lovable\.dev\/projects\//.test(String(body?.page_url||""))?String(body.page_url):`https://lovable.dev/projects/${projectId}`;
    const state=await makeState(projectId,returnUrl,"",userId);
    return json({connected:false,requires_github_authorization:true,multi_user:true,recovery_state:state,authorize_url:`https://github.com/apps/${env("GITHUB_APP_SLUG")}/installations/new?state=${encodeURIComponent(state)}`});
  }
  let safeBody=body;
  if(!ownIds.size&&!ownership.project?.user_id)safeBody={...body,repository_url:""};
  const core=await callCore(req,action,body,safeBody);
  const data=await readCoreResponse(core);
  const returnedSession=String(data?.session_token||"");
  if(returnedSession){const claim=await claimProjectForUser(projectId,userId,returnedSession);if(!claim.ok)return json({connected:false,error:"A conexão GitHub não pôde ser atribuída à sua conta MSK. Autorize o GitHub novamente.",code:claim.code},403);}
  return new Response(JSON.stringify({...data,multi_user:true}),{status:core.status,headers:cors});
}
if(action==="bind-existing"){const installationId=Number(body?.installation_id||0);if(!Number.isInteger(installationId)||installationId<=0)return json({connected:false,error:"Instalação GitHub inválida."},400);const existing=await installationOwner(installationId);if(existing?.user_id&&String(existing.user_id)!==userId)return json({connected:false,error:"Essa instalação GitHub já pertence a outra conta MSK.",code:"GITHUB_INSTALLATION_OWNERSHIP_MISMATCH"},403);if(!String(body?.recovery_state||"").trim())return json({connected:false,error:"Confirmação segura do GitHub ausente. Clique em conectar novamente.",code:"RECOVERY_STATE_REQUIRED"},401);const core=await callCore(req,action,body);const data=await readCoreResponse(core);const returnedSession=String(data?.session_token||"");if(!core.ok||!data?.connected||!returnedSession)return new Response(JSON.stringify(data),{status:core.status,headers:cors});const claim=await claimProjectForUser(projectId,userId,returnedSession);if(!claim.ok)return json({connected:false,error:"Não foi possível vincular esta instalação GitHub à sua conta MSK.",code:claim.code},403);return json({...data,connected:true,multi_user:true});}
if(action==="status"){ownership=await ownedProject(projectId,userId);if(!ownership.ok)return json({connected:false,error:"Esta conexão GitHub pertence a outra conta MSK.",code:ownership.code},403);if(!ownership.project?.user_id)return json({connected:false,requires_github_authorization:true,code:"GITHUB_RECONNECT_REQUIRED"});const core=await callCore(req,action,body);const data=await readCoreResponse(core);return new Response(JSON.stringify(data),{status:core.status,headers:cors});}
if(action!=="chat"){ownership=await ownedProject(projectId,userId);if(!ownership.ok||!ownership.project?.user_id)return json({connected:false,error:"Conecte o seu GitHub nesta conta MSK antes de editar.",code:"GITHUB_RECONNECT_REQUIRED"},401);}const core=await callCore(req,action,body);const data=await readCoreResponse(core);const taskId=String(data?.task_id||body?.task_id||"");if(/^[0-9a-f-]{36}$/i.test(taskId)){await db.from("msk_tasks").update({user_id:userId}).eq("id",taskId).eq("lovable_project_id",projectId).is("user_id",null);const {data:task}=await db.from("msk_tasks").select("user_id").eq("id",taskId).maybeSingle();if(task?.user_id&&String(task.user_id)!==userId)return json({error:"Esta tarefa pertence a outra conta MSK.",code:"TASK_OWNERSHIP_MISMATCH"},403);}return new Response(JSON.stringify(data),{status:core.status,headers:cors});});