import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, apikey, content-type, x-msk-session, x-msk-license, x-msk-installation-id, x-msk-extension-version, x-msk-extension-id, x-msk-build-id, x-msk-integrity-root, x-msk-build-fingerprint, x-msk-device-session, x-msk-proof-version, x-msk-timestamp, x-msk-counter, x-msk-body-sha256, x-msk-signature, x-msk-target, x-msk-action","Access-Control-Allow-Methods":"POST,OPTIONS"};
const json=(body,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,"Content-Type":"application/json"}});
const enc=new TextEncoder();
const b64=bytes=>btoa(String.fromCharCode(...bytes)).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/,"");
const sha=async value=>b64(new Uint8Array(await crypto.subtle.digest("SHA-256",enc.encode(value))));
const proofHeaders=["x-msk-installation-id","x-msk-extension-version","x-msk-extension-id","x-msk-build-id","x-msk-integrity-root","x-msk-build-fingerprint","x-msk-device-session","x-msk-proof-version","x-msk-timestamp","x-msk-counter","x-msk-body-sha256","x-msk-signature","x-msk-target","x-msk-action"];
async function verifyOriginalDevice(req,rawBody){const buildId=String(req.headers.get("x-msk-build-id")||"").trim();if(!buildId)return{ok:true,legacy:true};const auth=req.headers.get("authorization")||req.headers.get("x-msk-license")||"";if(!auth||proofHeaders.some(name=>!req.headers.get(name)))return{ok:false,status:401,code:"DEVICE_IDENTITY_REQUIRED"};const bodyHash=await sha(rawBody);if(bodyHash!==req.headers.get("x-msk-body-sha256"))return{ok:false,status:401,code:"SECURITY_BODY_MISMATCH"};const headers={Authorization:auth,"Content-Type":"application/json"};for(const name of proofHeaders)headers[name]=String(req.headers.get(name)||"");try{const response=await fetch("https://msksystem.online/api/extension/device-authorize",{method:"POST",headers,body:JSON.stringify({body_sha256:bodyHash})});const data=await response.json().catch(()=>({}));if(response.ok&&data?.device_authorized)return{ok:true};if(data?.blocked||data?.code==="INSTALLATION_BLOCKED")return{ok:false,status:403,code:"INSTALLATION_BLOCKED"};return{ok:false,status:response.status||403,code:String(data?.code||"MSK_SECURITY_REJECTED")};}catch{return{ok:false,status:503,code:"MSK_SECURITY_UNAVAILABLE"};}}
const attachmentArray=value=>Array.isArray(value)?value.slice(0,8):[];
const normalize=value=>String(value||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();
const sanitizeCommand=value=>String(value||"").replace(/\r\n/g,"\n").replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F\u007F]/g,"").trim();
const hasEditIntent=value=>{const text=normalize(value);return /\b(mud|troc|alter|corrig|adicion|remov|cri|fac|implement|edit|ajust|coloc|tir|exclu|delet|renome|configur|integr|conect|desenvolv|mont|atualiz|apliqu|substitu|arrum|consert|ger|refator|otimiz|migr|prote|bloque|liber|salv|cadastr|instal|import|usar)\w*/.test(text)||/\b(quero|preciso)\b.{0,80}\b(checkout|carrinho|pix|pagamento|api|webhook|site|pagina|sistema|dashboard|banco|login|componente|efeito|fundo|animacao)\b/.test(text);};
const looksLikeDocumentation=value=>/(?:documenta[cç][aã]o|endpoint|headers?|payload|response|request|webhook|bearer|oauth|api key|\b(?:GET|POST|PUT|PATCH|DELETE)\s+\/)/i.test(value);
async function analyzeAttachments(supabaseUrl,command,attachments){if(!attachments.length)return{ok:true,context:"",attachment_count:0};const serviceRole=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";if(!serviceRole)return{ok:false,status:503,code:"MSK_ATTACHMENT_SERVICE_UNAVAILABLE",error:"O leitor seguro de documentação está indisponível."};try{const response=await fetch(`${supabaseUrl}/functions/v1/msk-attachment-analyze`,{method:"POST",headers:{Authorization:`Bearer ${serviceRole}`,"Content-Type":"application/json"},body:JSON.stringify({command,attachments})});const data=await response.json().catch(()=>({}));if(!response.ok||data?.ok===false)return{ok:false,status:response.status,code:String(data?.code||"MSK_ATTACHMENT_ANALYSIS_FAILED"),error:String(data?.error||"Não foi possível analisar a documentação.")};return data;}catch{return{ok:false,status:503,code:"MSK_ATTACHMENT_ANALYSIS_FAILED",error:"Não foi possível analisar a documentação agora."};}}
function internalHeaders(req){const out={"Content-Type":"application/json"};for(const name of ["authorization","apikey","x-msk-session","x-msk-license"]){const value=req.headers.get(name);if(value)out[name]=value;}return out;}
async function enforcePreflight(req,supabaseUrl,rawBody,parsed){const response=await fetch(`${supabaseUrl}/functions/v1/msk-agent-preflight?action=preflight`,{method:"POST",headers:internalHeaders(req),body:rawBody});const text=await response.text();let data={};try{data=text?JSON.parse(text):{};}catch{}if(!response.ok||data?.ready!==true)return new Response(text||JSON.stringify({ready:false,blockers:[{code:"PREFLIGHT_FAILED",message:"O pre-flight não autorizou a execução."}],warnings:[]}),{status:response.status||409,headers:{...cors,"Content-Type":"application/json"}});if(data?.context?.force_pr===true&&parsed?.direct_commit!==false)return json({ready:false,blockers:[{code:"BRANCH_PROTECTED",message:"A branch é protegida. Reenvie em modo branch/PR.",action:"Usar Pull Request"}],warnings:data?.warnings||[],context:data?.context||null},409);return null;}
const dbUrl=(Deno.env.get("SUPABASE_URL")||"").replace(/\/$/,"");
const dbRole=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";
const queueDb=dbUrl&&dbRole?createClient(dbUrl,dbRole):null;
const aiTransientCodes=new Set(["AI_RATE_LIMIT","AI_UPSTREAM_UNAVAILABLE","AI_NETWORK_UNAVAILABLE","AI_REQUEST_TIMEOUT","AI_WAITING_RETRY"]);
const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function markAiWaiting(parsed,code,attempt){if(!queueDb)return;const taskId=String(parsed?.task_id||""),projectId=String(parsed?.lovable_project_id||"");if(!/^[0-9a-f-]{36}$/i.test(taskId)||!/^[0-9a-f-]{36}$/i.test(projectId))return;const{data:task}=await queueDb.from("msk_tasks").select("user_id").eq("id",taskId).maybeSingle();if(!task?.user_id)return;await queueDb.from("msk_tasks").update({status:"queued_waiting_ai",error:null,error_code:code,error_stage:"analyzing",progress_message:"IA ocupada · aguardando automaticamente",updated_at:new Date().toISOString()}).eq("id",taskId);await queueDb.from("msk_ai_retry_queue").upsert({task_id:taskId,user_id:task.user_id,lovable_project_id:projectId,reason_code:code,attempt_count:attempt,next_retry_at:new Date(Date.now()+Math.min(120000,15000*Math.max(1,attempt))).toISOString(),updated_at:new Date().toISOString()},{onConflict:"task_id"});}
async function clearAiWaiting(parsed){if(!queueDb)return;const id=String(parsed?.task_id||"");if(/^[0-9a-f-]{36}$/i.test(id))await queueDb.from("msk_ai_retry_queue").delete().eq("task_id",id);}
async function callAgentResilient(req,supabaseUrl,upstreamAction,parsed){const delays=upstreamAction==="run"?[0,2500,6000,12000,22000]:[0];let last=null;for(let attempt=0;attempt<delays.length;attempt++){if(delays[attempt])await wait(delays[attempt]);const upstream=await fetch(`${supabaseUrl}/functions/v1/msk-agent?action=${encodeURIComponent(upstreamAction)}`,{method:"POST",headers:internalHeaders(req),body:JSON.stringify(parsed)});const text=await upstream.text();let data={};try{data=text?JSON.parse(text):{};}catch{data={error:text};}last={upstream,text,data};const code=String(data?.code||"").toUpperCase();if(!aiTransientCodes.has(code)){if(upstream.ok)await clearAiWaiting(parsed);return last;}await markAiWaiting(parsed,code,attempt+1);}return last;}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(req.method!=="POST")return json({ok:false,code:"METHOD_NOT_ALLOWED"},405);const url=new URL(req.url),action=url.searchParams.get("action")||"status",supabaseUrl=(Deno.env.get("SUPABASE_URL")||"").replace(/\/$/,"");if(!supabaseUrl)return json({ok:false,code:"MSK_UNAVAILABLE",error:"O MSK está temporariamente indisponível."},503);try{const rawBody=await req.text();const device=await verifyOriginalDevice(req,rawBody);if(!device.ok)return json({ok:false,code:device.code,stage:"transport",error:device.code==="INSTALLATION_BLOCKED"?"Esta instalação foi bloqueada pela segurança MSK.":"A autorização segura desta instalação foi recusada."},device.status||403);let parsed={};try{parsed=rawBody?JSON.parse(rawBody):{};}catch{return json({ok:false,code:"INVALID_JSON",error:"O corpo da solicitação é inválido."},400);}if(action==="run"){const blocked=await enforcePreflight(req,supabaseUrl,rawBody,parsed);if(blocked)return blocked;}let upstreamAction=action;if(action==="run"||action==="chat"){const originalCommand=sanitizeCommand(parsed?.client_original_command||parsed?.original_command||parsed?.message||parsed?.command||"");if(!originalCommand)return json({ok:false,code:"EMPTY_COMMAND",error:"Comando vazio."},400);const attachments=attachmentArray(parsed?.attachments),longDocumentation=action==="run"&&originalCommand.length>9000&&looksLikeDocumentation(originalCommand),analysisAttachments=[...attachments];if(longDocumentation)analysisAttachments.push({id:"inline_documentation",name:"documentacao-colada.md",mime:"text/markdown",kind:"text",size:originalCommand.length,text:originalCommand});let context="",attachmentCount=0;if(analysisAttachments.length){const analyzed=await analyzeAttachments(supabaseUrl,originalCommand.slice(0,4000),analysisAttachments);if(!analyzed?.ok)return json({ok:false,code:analyzed.code||"MSK_ATTACHMENT_ANALYSIS_FAILED",stage:"analyzing",retryable:true,error:analyzed.error||"Não foi possível analisar a documentação."},Number(analyzed.status||422));context=String(analyzed?.context||"").trim();attachmentCount=Number(analyzed?.attachment_count||analysisAttachments.length);}const baseOriginal=longDocumentation?originalCommand.slice(0,4300):originalCommand.slice(0,11600),maxContext=Math.max(0,11600-baseOriginal.length-2),compactContext=context.slice(0,maxContext),executionCommand=compactContext?`${baseOriginal}\n\n${compactContext}`.trim():baseOriginal;parsed.client_original_command=originalCommand;parsed.command=executionCommand;parsed.original_command=executionCommand;parsed.documentation_compacted=longDocumentation;parsed.attachment_context_used=!!context;parsed.attachment_count=attachmentCount;delete parsed.attachments;delete parsed.history;delete parsed.active_skill;delete parsed.reinforced_command;if(action==="run"&&!hasEditIntent(originalCommand)){upstreamAction="chat";parsed.message=executionCommand||originalCommand;}}
const called=await callAgentResilient(req,supabaseUrl,upstreamAction,parsed);const upstream=called.upstream,text=called.text,data=called.data||{};const code=String(data?.code||"").toUpperCase();if(upstreamAction==="run"&&aiTransientCodes.has(code)){await markAiWaiting(parsed,code,5);return json({ok:false,queued:true,retryable:true,ai_backpressure:true,code:"AI_WAITING_RETRY",upstream_code:code,stage:"analyzing",task_id:parsed?.task_id,retry_after_ms:45000,error:"A MSK IA está temporariamente ocupada. A tarefa foi preservada e será retomada automaticamente."},202);}if(upstream.status===546)return json({ok:false,code:"MSK_EXECUTION_TIMEOUT",stage:"transport",retryable:true,task_id:parsed?.task_id,error:"A execução excedeu a janela de resposta. A tarefa pode continuar e deve ser reconciliada pelo task_id."},504);return new Response(text,{status:upstream.status,headers:{...cors,"Content-Type":upstream.headers.get("content-type")||"application/json"}});}catch(error){console.error("MSK public transport gateway",error instanceof Error?error.message:"unknown");return json({ok:false,code:"MSK_TEMPORARILY_UNAVAILABLE",stage:"transport",retryable:true,error:"A comunicação com o agente ficou temporariamente indisponível. A MSK deve confirmar a tarefa pelo task_id antes de exibir falha."},503);}});