import { b64, unb64, enc, dec, env, db, sha } from "./common.ts";
const hmac = async (v: string) => { const k = await crypto.subtle.importKey("raw", enc.encode(env("MSK_STATE_SECRET")), { name: "HMAC", hash: "SHA-256" }, false, ["sign"]); return b64(new Uint8Array(await crypto.subtle.sign("HMAC", k, enc.encode(v)))); };
export const makeState = async (projectId: string, returnUrl: string, repository: string, userId: string) => { const p = b64(enc.encode(JSON.stringify({ projectId, returnUrl, repository, userId, exp: Date.now() + 900000 }))); return `${p}.${await hmac(p)}`; };
export const readState = async (s: string) => { const [p, q] = s.split("."); if (!p || !q || q !== await hmac(p)) throw new Error("STATE_INVALID"); const d = JSON.parse(dec.decode(unb64(p))); if (Number(d?.exp || 0) < Date.now() || !/^https:\/\/lovable\.dev\/projects\//.test(String(d?.returnUrl || ""))) throw new Error("STATE_EXPIRED"); return d; };
const derLen = (n: number) => n < 128 ? new Uint8Array([n]) : (() => { const a: number[] = []; for (let v = n; v > 0; v >>>= 8) a.unshift(v & 255); return new Uint8Array([128 | a.length, ...a]); })();
const join = (...p: Uint8Array[]) => { const o = new Uint8Array(p.reduce((s, x) => s + x.length, 0)); let n = 0; for (const x of p) { o.set(x, n); n += x.length; } return o; };
const wrap = (t: number, v: Uint8Array) => join(new Uint8Array([t]), derLen(v.length), v);
const pkcs1 = (r: Uint8Array) => wrap(48, join(new Uint8Array([2, 1, 0]), new Uint8Array([48, 13, 6, 9, 42, 134, 72, 134, 247, 13, 1, 1, 1, 5, 0]), wrap(4, r)));
const b64bytes = (v: string) => Uint8Array.from(atob(v.replace(/\s/g, "")), c => c.charCodeAt(0));
async function appKey() { let v = env("GITHUB_APP_PRIVATE_KEY").trim().replace(/\\r\\n/g, "\n").replace(/\\n/g, "\n"); const m = v.match(/-----BEGIN ([A-Z ]*PRIVATE KEY)-----([\s\S]*?)-----END \1-----/); try { const alg = { name: "RSASSA-PKCS1-v1_5", hash: "SHA-256" } as const; if (m) { const raw = b64bytes(m[2]); return await crypto.subtle.importKey("pkcs8", m[1] === "RSA PRIVATE KEY" ? pkcs1(raw) : raw, alg, false, ["sign"]); } return await crypto.subtle.importKey("pkcs8", b64bytes(v), alg, false, ["sign"]); } catch (e) { console.error("MSK GitHub key invalid", e instanceof Error ? e.name : "invalid"); throw new Error("GITHUB_APP_CREDENTIALS_INVALID"); } }
async function appJwt() { const n = Math.floor(Date.now() / 1000), h = b64(enc.encode(JSON.stringify({ alg: "RS256", typ: "JWT" }))), p = b64(enc.encode(JSON.stringify({ iat: n - 30, exp: n + 540, iss: env("GITHUB_APP_ID") }))), u = `${h}.${p}`; return `${u}.${b64(new Uint8Array(await crypto.subtle.sign("RSASSA-PKCS1-v1_5", await appKey(), enc.encode(u))))}`; }
export async function installation(id: number) { const r = await fetch(`https://api.github.com/app/installations/${id}`, { headers: { Authorization: `Bearer ${await appJwt()}`, Accept: "application/vnd.github+json", "X-GitHub-Api-Version": "2022-11-28" } }); if (r.status === 404) return null; if (!r.ok) throw new Error(`GitHub installation ${r.status}`); const d = await r.json(); return d?.suspended_at ? null : d; }
export async function instToken(id: number) { const r = await fetch(`https://api.github.com/app/installations/${id}/access_tokens`, { method: "POST", headers: { Authorization: `Bearer ${await appJwt()}`, Accept: "application/vnd.github+json", "X-GitHub-Api-Version": "2022-11-28" } }); if (!r.ok) throw new Error("GitHub installation token failed"); return String((await r.json()).token); }
export async function gh(t: string, path: string, init: RequestInit = {}) { const r = await fetch(`https://api.github.com${path}`, { ...init, headers: { Authorization: `Bearer ${t}`, Accept: "application/vnd.github+json", "Content-Type": "application/json", "X-GitHub-Api-Version": "2022-11-28", ...(init.headers || {}) } }); if (!r.ok) throw new Error(`GitHub ${r.status}: ${await r.text()}`); return r.status === 204 ? null : r.json(); }
export async function validSession(pid: string, t: string) { if (!t) return false; const { data } = await db.from("msk_projects").select("session_token_hash").eq("lovable_project_id", pid).maybeSingle(); return !!data?.session_token_hash && data.session_token_hash === await sha(t); }
export async function chooseRepo(id: number, _name = "", preferred = "") {
  const t = await instToken(id);
  const d = await gh(t, "/installation/repositories?per_page=100");
  const rs = d.repositories || [];
  const p = String(preferred || "").toLowerCase().replace(/^https:\/\/github\.com\//, "").replace(/\.git$/, "").replace(/^\/+|\/+$/g, "");
  const repo = p ? rs.find((r: any) => String(r.full_name).toLowerCase() === p) : (rs.length === 1 ? rs[0] : null);
  return { token: t, repo, candidates: rs.map((r: any) => r.full_name), exact_binding: !!p && !!repo };
}
