-- MSK AI Global Training
-- Persistent, versioned operational instructions controlled by Super Admin.
-- Additive migration: does not replace existing AI settings or user prompts.

create or replace function public.is_super_admin(_user_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.user_roles ur
    where ur.user_id = _user_id
      and ur.role = 'super_admin'
  );
$$;

revoke all on function public.is_super_admin(uuid) from public;
grant execute on function public.is_super_admin(uuid) to authenticated, service_role;

create table if not exists public.msk_ai_global_training (
  id uuid primary key default gen_random_uuid(),
  version bigint generated by default as identity unique,
  title text not null check (char_length(title) between 1 and 160),
  instruction text not null check (char_length(instruction) between 1 and 20000),
  category text not null default 'general' check (category in ('general','coding','security','behavior','quality','support','business')),
  priority integer not null default 100 check (priority between 1 and 1000),
  scope text not null default 'all_users' check (scope = 'all_users'),
  status text not null default 'draft' check (status in ('draft','active','disabled','archived')),
  ai_acknowledgement text,
  created_by uuid references auth.users(id) on delete set null,
  published_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  published_at timestamptz,
  disabled_at timestamptz,
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists msk_ai_global_training_runtime_idx
  on public.msk_ai_global_training (status, priority, version);

create index if not exists msk_ai_global_training_created_idx
  on public.msk_ai_global_training (created_at desc);

create table if not exists public.msk_ai_global_training_audit (
  id uuid primary key default gen_random_uuid(),
  training_id uuid references public.msk_ai_global_training(id) on delete set null,
  version bigint,
  action text not null check (action in ('created','updated','previewed','published','disabled','archived')),
  actor_id uuid references auth.users(id) on delete set null,
  snapshot jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists msk_ai_global_training_audit_training_idx
  on public.msk_ai_global_training_audit (training_id, created_at desc);

create or replace function public.msk_ai_global_training_touch_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_msk_ai_global_training_updated_at on public.msk_ai_global_training;
create trigger trg_msk_ai_global_training_updated_at
before update on public.msk_ai_global_training
for each row execute function public.msk_ai_global_training_touch_updated_at();

alter table public.msk_ai_global_training enable row level security;
alter table public.msk_ai_global_training_audit enable row level security;

-- Only Super Admin may inspect or mutate training directly.
-- Server-side functions still validate Super Admin before performing writes.
drop policy if exists msk_ai_global_training_super_admin_select on public.msk_ai_global_training;
create policy msk_ai_global_training_super_admin_select
on public.msk_ai_global_training
for select
to authenticated
using (public.is_super_admin(auth.uid()));

drop policy if exists msk_ai_global_training_super_admin_insert on public.msk_ai_global_training;
create policy msk_ai_global_training_super_admin_insert
on public.msk_ai_global_training
for insert
to authenticated
with check (public.is_super_admin(auth.uid()));

drop policy if exists msk_ai_global_training_super_admin_update on public.msk_ai_global_training;
create policy msk_ai_global_training_super_admin_update
on public.msk_ai_global_training
for update
to authenticated
using (public.is_super_admin(auth.uid()))
with check (public.is_super_admin(auth.uid()));

drop policy if exists msk_ai_global_training_super_admin_delete on public.msk_ai_global_training;
create policy msk_ai_global_training_super_admin_delete
on public.msk_ai_global_training
for delete
to authenticated
using (public.is_super_admin(auth.uid()));

drop policy if exists msk_ai_global_training_audit_super_admin_select on public.msk_ai_global_training_audit;
create policy msk_ai_global_training_audit_super_admin_select
on public.msk_ai_global_training_audit
for select
to authenticated
using (public.is_super_admin(auth.uid()));

drop policy if exists msk_ai_global_training_audit_super_admin_insert on public.msk_ai_global_training_audit;
create policy msk_ai_global_training_audit_super_admin_insert
on public.msk_ai_global_training_audit
for insert
to authenticated
with check (public.is_super_admin(auth.uid()));

grant select, insert, update, delete on public.msk_ai_global_training to authenticated;
grant select, insert on public.msk_ai_global_training_audit to authenticated;
grant usage, select on sequence public.msk_ai_global_training_version_seq to authenticated;

grant all on public.msk_ai_global_training to service_role;
grant all on public.msk_ai_global_training_audit to service_role;
grant usage, select on sequence public.msk_ai_global_training_version_seq to service_role;
