// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env['VITE_SUPABASE_URL'] || process.env['SUPABASE_URL'];
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env['VITE_SUPABASE_PUBLISHABLE_KEY'] || process.env['SUPABASE_PUBLISHABLE_KEY'];

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: brokeredPreviewStorage(),
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;
let _authProxy: ReturnType<typeof createSupabaseClient>['auth'] | undefined;

/**
 * O Lovable Cloud possui OAuth próprio para Apple. A tela de autenticação antiga
 * chamava Apple pelo Supabase, enquanto Google já usava Lovable Auth. Isso fazia
 * Apple depender de um provider duplicado/configurado separadamente no Supabase.
 *
 * Interceptamos apenas Apple e mantemos GitHub/Discord e demais providers no
 * fluxo nativo do Supabase. O import dinâmico evita ciclo durante a inicialização,
 * já que a integração Lovable também usa este cliente para persistir a sessão.
 */
function getAuthProxy(client: ReturnType<typeof createSupabaseClient>) {
  if (_authProxy) return _authProxy;
  const auth = client.auth;

  _authProxy = new Proxy(auth, {
    get(target, prop) {
      if (prop === 'signInWithOAuth') {
        return async (credentials: any) => {
          if (credentials?.provider === 'apple') {
            const redirectUri = credentials?.options?.redirectTo as string | undefined;
            const { lovable } = await import('../lovable');
            const result = await lovable.auth.signInWithOAuth(
              'apple',
              redirectUri ? { redirect_uri: redirectUri } : undefined,
            );

            return {
              data: { provider: 'apple', url: null },
              error: result.error ?? null,
            } as any;
          }

          return target.signInWithOAuth(credentials);
        };
      }

      const value = Reflect.get(target, prop, target);
      return typeof value === 'function' ? value.bind(target) : value;
    },
  }) as ReturnType<typeof createSupabaseClient>['auth'];

  return _authProxy;
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop) {
    if (!_supabase) _supabase = createSupabaseClient();
    if (prop === 'auth') return getAuthProxy(_supabase);

    const value = Reflect.get(_supabase, prop, _supabase);
    return typeof value === 'function' ? value.bind(_supabase) : value;
  },
});
