// This file is automatically generated. Do not edit it directly.
// Server-side Supabase clients.
// - supabaseServer: publishable key, respects RLS (safe for public/server reads).
// - supabaseAdmin: uses a privileged server key when available. If Lovable Cloud
//   does not expose one, authenticated requests fall back to the caller JWT + RLS.
import { createClient } from '@supabase/supabase-js';
import { getRequest } from '@tanstack/react-start/server';
import type { Database } from './types';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function env(...names: string[]): string | undefined {
  for (const name of names) {
    const value = process.env[name];
    if (typeof value === 'string' && value.trim()) return value.trim();
  }
  return undefined;
}

function getSupabaseUrl() {
  return env('SUPABASE_URL', 'VITE_SUPABASE_URL');
}

function getPublishableKey() {
  return env(
    'SUPABASE_PUBLISHABLE_KEY',
    'VITE_SUPABASE_PUBLISHABLE_KEY',
    'SUPABASE_ANON_KEY',
    'VITE_SUPABASE_ANON_KEY',
  );
}

function getPrivilegedKey() {
  // Supabase supports the legacy JWT service_role key and the newer sb_secret_ key.
  // Never add VITE_ aliases here: privileged keys must remain server-only.
  return env('SUPABASE_SERVICE_ROLE_KEY', 'SUPABASE_SECRET_KEY');
}

function baseAuthOptions() {
  return {
    storage: undefined,
    persistSession: false,
    autoRefreshToken: false,
  } as const;
}

function createSupabaseServerClient() {
  const url = getSupabaseUrl();
  const key = getPublishableKey();

  if (!url || !key) {
    const missing = [
      ...(!url ? ['SUPABASE_URL/VITE_SUPABASE_URL'] : []),
      ...(!key ? ['SUPABASE_PUBLISHABLE_KEY/VITE_SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase public environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(url, key, {
    global: { fetch: createSupabaseFetch(key) },
    auth: baseAuthOptions(),
  });
}

function createPrivilegedSupabaseClient(url: string, privilegedKey: string) {
  return createClient<Database>(url, privilegedKey, {
    global: { fetch: createSupabaseFetch(privilegedKey) },
    auth: baseAuthOptions(),
  });
}

/**
 * Safe fallback for Lovable Cloud runtimes that do not expose the Supabase
 * service-role/secret key to the TanStack server process.
 *
 * The caller JWT is forwarded with the publishable key, so every query remains
 * protected by Supabase RLS. This is intentionally NOT cached: caching a user
 * bearer token in a module singleton could leak one admin session into another.
 */
function createAuthenticatedRequestClient() {
  const url = getSupabaseUrl();
  const publishableKey = getPublishableKey();
  const request = getRequest();
  const authorization = request?.headers?.get('authorization')?.trim() ?? '';

  if (!url || !publishableKey || !authorization.startsWith('Bearer ')) {
    const missing = [
      ...(!url ? ['SUPABASE_URL/VITE_SUPABASE_URL'] : []),
      ...(!publishableKey ? ['SUPABASE_PUBLISHABLE_KEY/VITE_SUPABASE_PUBLISHABLE_KEY'] : []),
      ...(!authorization.startsWith('Bearer ') ? ['authenticated request token'] : []),
    ];
    const message =
      `Supabase privileged key is unavailable and authenticated RLS fallback could not start: ${missing.join(', ')}.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(url, publishableKey, {
    global: {
      fetch: createSupabaseFetch(publishableKey),
      headers: { Authorization: authorization },
    },
    auth: baseAuthOptions(),
  });
}

let _supabaseServer: ReturnType<typeof createSupabaseServerClient> | undefined;
let _privilegedSupabaseAdmin: ReturnType<typeof createPrivilegedSupabaseClient> | undefined;

function resolveSupabaseAdminClient() {
  const url = getSupabaseUrl();
  const privilegedKey = getPrivilegedKey();

  if (url && privilegedKey) {
    if (!_privilegedSupabaseAdmin) {
      _privilegedSupabaseAdmin = createPrivilegedSupabaseClient(url, privilegedKey);
    }
    return _privilegedSupabaseAdmin;
  }

  // No service role in Lovable runtime: use request-scoped JWT + RLS instead of
  // crashing the whole Super Admin page.
  return createAuthenticatedRequestClient();
}

// Server-side public client. Uses the publishable key and therefore respects RLS.
export const supabaseServer = new Proxy({} as ReturnType<typeof createSupabaseServerClient>, {
  get(_, prop, receiver) {
    if (!_supabaseServer) _supabaseServer = createSupabaseServerClient();
    return Reflect.get(_supabaseServer, prop, receiver);
  },
});

// Server-side admin facade. Uses true privileged credentials when present;
// otherwise falls back to the authenticated request and lets RLS enforce access.
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseServerClient>, {
  get(_, prop, receiver) {
    const client = resolveSupabaseAdminClient();
    return Reflect.get(client, prop, receiver);
  },
});
