// This file is automatically generated. Do not edit it directly.
// Server-side Supabase clients.
// - supabaseServer: publishable key, respects RLS (safe for public/server reads).
// - supabaseAdmin: privileged key, bypasses RLS (trusted server operations only).
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function env(...names: string[]): string | undefined {
  for (const name of names) {
    const value = process.env[name];
    if (typeof value === 'string' && value.trim()) return value.trim();
  }
  return undefined;
}

function getSupabaseUrl() {
  return env('SUPABASE_URL', 'VITE_SUPABASE_URL');
}

function getPublishableKey() {
  return env(
    'SUPABASE_PUBLISHABLE_KEY',
    'VITE_SUPABASE_PUBLISHABLE_KEY',
    'SUPABASE_ANON_KEY',
    'VITE_SUPABASE_ANON_KEY',
  );
}

function getPrivilegedKey() {
  // Supabase supports the legacy JWT service_role key and the newer sb_secret_ key.
  // Lovable/TanStack projects may expose either name depending on how the backend was connected.
  return env('SUPABASE_SERVICE_ROLE_KEY', 'SUPABASE_SECRET_KEY');
}

function createSupabaseServerClient() {
  const url = getSupabaseUrl();
  const key = getPublishableKey();

  if (!url || !key) {
    const missing = [
      ...(!url ? ['SUPABASE_URL/VITE_SUPABASE_URL'] : []),
      ...(!key ? ['SUPABASE_PUBLISHABLE_KEY/VITE_SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase public environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(url, key, {
    global: { fetch: createSupabaseFetch(key) },
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    },
  });
}

function createSupabaseAdminClient() {
  const url = getSupabaseUrl();
  const privilegedKey = getPrivilegedKey();

  if (!url || !privilegedKey) {
    const missing = [
      ...(!url ? ['SUPABASE_URL/VITE_SUPABASE_URL'] : []),
      ...(!privilegedKey ? ['SUPABASE_SERVICE_ROLE_KEY ou SUPABASE_SECRET_KEY'] : []),
    ];
    const message =
      `Missing privileged Supabase server environment variable(s): ${missing.join(', ')}. ` +
      'Configure the server-only Supabase secret in Lovable Cloud → Secrets. Never expose this key with a VITE_ prefix.';
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(url, privilegedKey, {
    global: {
      fetch: createSupabaseFetch(privilegedKey),
    },
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    },
  });
}

let _supabaseServer: ReturnType<typeof createSupabaseServerClient> | undefined;
let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

// Server-side public client. Uses the publishable key and therefore respects RLS.
export const supabaseServer = new Proxy({} as ReturnType<typeof createSupabaseServerClient>, {
  get(_, prop, receiver) {
    if (!_supabaseServer) _supabaseServer = createSupabaseServerClient();
    return Reflect.get(_supabaseServer, prop, receiver);
  },
});

// Server-side privileged client. SECURITY: server-only; never expose its key to browser code.
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});
