// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function envConfig() {
  const url = import.meta.env['VITE_SUPABASE_URL'] || process.env['SUPABASE_URL'];
  const key = import.meta.env['VITE_SUPABASE_PUBLISHABLE_KEY'] || process.env['SUPABASE_PUBLISHABLE_KEY'];
  return { url, key };
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

async function assertSupabaseOAuthProvider(provider: 'github' | 'discord') {
  const { url, key } = envConfig();
  if (!url || !key) return;

  try {
    const response = await fetch(`${url}/auth/v1/settings`, {
      headers: { apikey: key },
    });
    if (!response.ok) return;

    const settings = (await response.json()) as {
      external?: Record<string, boolean | undefined>;
    };

    if (settings.external?.[provider] !== true) {
      const label = provider === 'github' ? 'GitHub' : 'Discord';
      throw new Error(
        `${label} OAuth não está configurado no Supabase. Ative o provider e use o callback ${url}/auth/v1/callback.`,
      );
    }
  } catch (error) {
    if (error instanceof Error && /OAuth não está configurado/.test(error.message)) throw error;
    // Falha temporária na consulta de settings não deve impedir um provider que esteja ativo.
  }
}

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const { url: SUPABASE_URL, key: SUPABASE_PUBLISHABLE_KEY } = envConfig();

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: brokeredPreviewStorage(),
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;
let _authProxy: ReturnType<typeof createSupabaseClient>['auth'] | undefined;

/**
 * Apple usa Lovable Auth, igual ao Google. GitHub e Discord permanecem no
 * Supabase OAuth, mas com verificação de provider e redirecionamento explícito.
 */
function getAuthProxy(client: ReturnType<typeof createSupabaseClient>) {
  if (_authProxy) return _authProxy;
  const auth = client.auth;

  _authProxy = new Proxy(auth, {
    get(target, prop) {
      if (prop === 'signInWithOAuth') {
        return async (credentials: any) => {
          if (credentials?.provider === 'apple') {
            const redirectUri = credentials?.options?.redirectTo as string | undefined;
            const { lovable } = await import('../lovable');
            const result = await lovable.auth.signInWithOAuth(
              'apple',
              redirectUri ? { redirect_uri: redirectUri } : undefined,
            );

            return {
              data: { provider: 'apple', url: null },
              error: result.error ?? null,
            } as any;
          }

          if (credentials?.provider === 'github' || credentials?.provider === 'discord') {
            const provider = credentials.provider as 'github' | 'discord';
            await assertSupabaseOAuthProvider(provider);

            const result = await target.signInWithOAuth({
              ...credentials,
              options: {
                ...(credentials.options ?? {}),
                skipBrowserRedirect: true,
              },
            });

            if (!result.error && result.data?.url && typeof window !== 'undefined') {
              window.location.assign(result.data.url);
            }
            return result;
          }

          return target.signInWithOAuth(credentials);
        };
      }

      const value = Reflect.get(target, prop, target);
      return typeof value === 'function' ? value.bind(target) : value;
    },
  }) as ReturnType<typeof createSupabaseClient>['auth'];

  return _authProxy;
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop) {
    if (!_supabase) _supabase = createSupabaseClient();
    if (prop === 'auth') return getAuthProxy(_supabase);

    const value = Reflect.get(_supabase, prop, _supabase);
    return typeof value === 'function' ? value.bind(_supabase) : value;
  },
});
